"""Render synchronized driver, KITTI, depth, labels, calibration and telemetry.

Examples:
    uv run --package fleetiq-training-roadface python tools/visualization/trip_player.py --list-trips
    uv run --package fleetiq-training-roadface python tools/visualization/trip_player.py --trip T01-Sample --mode window
    uv run --package fleetiq-training-roadface python tools/visualization/trip_player.py --trip T06-Sample --mode frame --frame 100
    uv run --package fleetiq-training-roadface python tools/visualization/trip_player.py --trip T02-Sample --mode video --end 300
"""

from __future__ import annotations

import argparse
import math
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import cv2
import numpy as np
from fleetiq_data import DatasetPaths
from fleetiq_data import discover_trips as discover_trip_records
from fleetiq_data import load_trip_document as load_organizer_trip_document
from fleetiq_data import parse_kitti_labels
from fleetiq_data import resolve_trip as resolve_trip_record


PROJECT_ROOT = Path(__file__).resolve().parents[2]
PRACTICE_ROOT = PROJECT_ROOT / "data" / "Practice_Dataset" / "Practice_Dataset"
REDACTED_ROOT = (
    PROJECT_ROOT
    / "data"
    / "Hackathon_Dataset_Redacted"
    / "Hackathon_Dataset_Redacted"
)

CANVAS_W = 1920
CANVAS_H = 1080

BG = (17, 23, 31)
PANEL = (27, 36, 47)
PANEL_ALT = (35, 45, 57)
GRID = (63, 77, 91)
TEXT = (233, 238, 243)
MUTED = (150, 164, 178)
CYAN = (232, 190, 47)
GREEN = (102, 211, 142)
AMBER = (54, 185, 245)
RED = (73, 73, 245)

CLASS_COLORS = {
    "Car": (57, 210, 255),
    "Van": (92, 201, 154),
    "Truck": (74, 166, 255),
    "Pedestrian": (91, 103, 255),
    "Cyclist": (255, 153, 99),
    "Motorcycle": (255, 122, 183),
    "Bus": (50, 230, 230),
    "LongVehicle": (180, 120, 255),
}


@dataclass(frozen=True)
class KittiLabel:
    object_type: str
    bbox: tuple[float, float, float, float]
    dimensions: tuple[float, float, float]
    location: tuple[float, float, float]
    rotation_y: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a synchronized FleetIQ driving dashboard.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--dataset-root",
        type=Path,
        default=PRACTICE_ROOT,
        help="Directory containing Txx trip folders.",
    )
    parser.add_argument("--trip", default="T01-Sample", help="Trip folder name.")
    parser.add_argument(
        "--label-dir-name",
        default="label_2",
        help="KITTI label folder under each trip's kitti directory.",
    )
    parser.add_argument(
        "--mode",
        choices=("window", "video", "frame"),
        default="window",
        help="Interactive playback, MP4 export, or one PNG.",
    )
    parser.add_argument("--list-trips", action="store_true", help="List detected trips.")
    parser.add_argument("--start", type=int, default=0, help="First frame index.")
    parser.add_argument("--end", type=int, help="Last frame index, inclusive.")
    parser.add_argument("--frame", type=int, help="Frame index used by frame mode.")
    parser.add_argument(
        "--fps",
        type=float,
        help="Playback/output FPS. Defaults to dataset metadata.",
    )
    parser.add_argument(
        "--speed",
        type=float,
        default=1.0,
        help="Interactive playback speed multiplier.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output PNG/MP4. A path under artifacts/renders is generated by default.",
    )
    parser.add_argument(
        "--depth-max",
        type=float,
        default=80.0,
        help="Depth visualization upper bound in meters.",
    )
    parser.add_argument(
        "--depth-policy",
        choices=("previous", "nearest"),
        default="previous",
        help="How sparse depth keyframes are aligned to camera frames.",
    )
    return parser.parse_args()


def discover_trips(root: Path) -> list[Path]:
    return [
        record.trip_dir for record in discover_trip_records(DatasetPaths(root))
    ]


def resolve_trip(root: Path, trip_name: str) -> Path:
    try:
        return resolve_trip_record(DatasetPaths(root), trip_name).trip_dir
    except FileNotFoundError:
        pass

    candidates = [
        path
        for search_root in (PRACTICE_ROOT, REDACTED_ROOT)
        for path in discover_trips(search_root)
        if path.name.lower() == trip_name.lower()
    ]
    if len(candidates) == 1:
        return candidates[0]
    raise FileNotFoundError(f"Trip '{trip_name}' was not found under {root}")


def load_trip_document(trip_dir: Path) -> dict[str, Any]:
    return load_organizer_trip_document(trip_dir)


def find_image(directory: Path, stems: Iterable[str]) -> Path | None:
    for stem in stems:
        for suffix in (".jpg", ".png", ".jpeg"):
            path = directory / f"{stem}{suffix}"
            if path.exists():
                return path
    return None


def read_image_or_placeholder(
    path: Path | None, width: int, height: int, message: str
) -> np.ndarray:
    image = cv2.imread(str(path)) if path is not None else None
    if image is None:
        image = np.full((height, width, 3), PANEL_ALT, dtype=np.uint8)
        draw_centered_text(image, message, height // 2, MUTED, 0.7)
    return image


def parse_calibration(path: Path) -> dict[str, np.ndarray]:
    calibration: dict[str, np.ndarray] = {}
    if not path.exists():
        return calibration
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        key, separator, values = raw_line.partition(":")
        if not separator:
            continue
        numbers = np.asarray([float(value) for value in values.split()], dtype=np.float64)
        if key.startswith("P") and numbers.size == 12:
            calibration[key] = numbers.reshape(3, 4)
        elif key == "R0_rect" and numbers.size == 9:
            calibration[key] = numbers.reshape(3, 3)
        elif numbers.size == 12:
            calibration[key] = numbers.reshape(3, 4)
        else:
            calibration[key] = numbers
    return calibration


def parse_labels(path: Path) -> list[KittiLabel]:
    return [
        KittiLabel(
            object_type=label.object_type,
            bbox=label.bbox,
            dimensions=label.dimensions,
            location=label.location,
            rotation_y=label.rotation_y,
        )
        for label in parse_kitti_labels(path)
    ]


def box_3d_corners(label: KittiLabel) -> np.ndarray:
    height, width, length = label.dimensions
    x, y, z = label.location
    x_corners = np.array(
        [length / 2, length / 2, -length / 2, -length / 2] * 2
    )
    y_corners = np.array([0, 0, 0, 0, -height, -height, -height, -height])
    z_corners = np.array(
        [width / 2, -width / 2, -width / 2, width / 2] * 2
    )
    cos_y = math.cos(label.rotation_y)
    sin_y = math.sin(label.rotation_y)
    rotation = np.array(
        [[cos_y, 0, sin_y], [0, 1, 0], [-sin_y, 0, cos_y]]
    )
    corners = rotation @ np.vstack([x_corners, y_corners, z_corners])
    corners += np.array([[x], [y], [z]])
    return corners


def project_points(points_3d: np.ndarray, projection: np.ndarray) -> np.ndarray | None:
    if points_3d.shape != (3, 8):
        return None
    homogeneous = np.vstack([points_3d, np.ones((1, points_3d.shape[1]))])
    projected = projection @ homogeneous
    if np.any(projected[2] <= 0.1):
        return None
    return (projected[:2] / projected[2]).T


def draw_labels(
    image: np.ndarray,
    labels: list[KittiLabel],
    projection: np.ndarray | None,
    draw_2d_fallback: bool,
) -> np.ndarray:
    result = image.copy()
    edges = (
        (0, 1), (1, 2), (2, 3), (3, 0),
        (4, 5), (5, 6), (6, 7), (7, 4),
        (0, 4), (1, 5), (2, 6), (3, 7),
    )
    for label in labels:
        color = CLASS_COLORS.get(label.object_type, (210, 210, 210))
        points = None
        if projection is not None and label.location[2] > 0.1:
            points = project_points(box_3d_corners(label), projection)
        if points is not None:
            integer_points = np.round(points).astype(int)
            for start, end in edges:
                cv2.line(
                    result,
                    tuple(integer_points[start]),
                    tuple(integer_points[end]),
                    color,
                    2,
                    cv2.LINE_AA,
                )
            label_anchor = tuple(integer_points[4])
        elif draw_2d_fallback:
            x1, y1, x2, y2 = (int(value) for value in label.bbox)
            cv2.rectangle(result, (x1, y1), (x2, y2), color, 2, cv2.LINE_AA)
            label_anchor = (x1, max(18, y1 - 4))
        else:
            continue

        distance = label.location[2]
        caption = (
            f"{label.object_type} {distance:.1f}m"
            if distance > 0.1
            else label.object_type
        )
        draw_tag(result, caption, label_anchor, color)
    return result


def nearest_depth_frame(
    available: np.ndarray, frame_id: int, policy: str
) -> int | None:
    if available.size == 0:
        return None
    if policy == "nearest":
        return int(available[np.argmin(np.abs(available - frame_id))])
    previous = available[available <= frame_id]
    return int(previous[-1] if previous.size else available[0])


def colorize_depth(path: Path | None, max_depth: float) -> tuple[np.ndarray, str]:
    if path is None or not path.exists():
        return (
            np.full((360, 640, 3), PANEL_ALT, dtype=np.uint8),
            "Depth unavailable",
        )
    depth = np.load(path).astype(np.float32)
    valid = np.isfinite(depth) & (depth > 0)
    clipped = np.clip(depth, 0, max_depth)
    normalized = ((1.0 - clipped / max_depth) * 255).astype(np.uint8)
    colored = cv2.applyColorMap(normalized, cv2.COLORMAP_TURBO)
    colored[~valid] = (15, 18, 23)
    median = float(np.median(depth[valid])) if np.any(valid) else math.nan
    return colored, f"median {format_number(median, 1)} m"


def safe_float(value: Any, default: float = math.nan) -> float:
    if value in ("Infinity", "-Infinity", None):
        return default
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def frame_value(frame: dict[str, Any], group: str, key: str) -> Any:
    section = frame.get(group, {})
    return section.get(key) if isinstance(section, dict) else None


def format_number(value: Any, digits: int = 2, suffix: str = "") -> str:
    number = safe_float(value)
    if not math.isfinite(number):
        return "--"
    return f"{number:.{digits}f}{suffix}"


def fit_image(image: np.ndarray, width: int, height: int) -> np.ndarray:
    source_h, source_w = image.shape[:2]
    scale = min(width / source_w, height / source_h)
    target_w = max(1, int(source_w * scale))
    target_h = max(1, int(source_h * scale))
    resized = cv2.resize(image, (target_w, target_h), interpolation=cv2.INTER_AREA)
    canvas = np.full((height, width, 3), (10, 14, 20), dtype=np.uint8)
    x = (width - target_w) // 2
    y = (height - target_h) // 2
    canvas[y : y + target_h, x : x + target_w] = resized
    return canvas


def paste_panel(
    canvas: np.ndarray,
    image: np.ndarray,
    x: int,
    y: int,
    width: int,
    height: int,
    title: str,
    subtitle: str = "",
) -> None:
    cv2.rectangle(canvas, (x, y), (x + width, y + height), PANEL, -1)
    cv2.rectangle(canvas, (x, y), (x + width, y + height), GRID, 1)
    content_y = y + 34
    content_h = height - 34
    canvas[content_y : y + height, x : x + width] = fit_image(
        image, width, content_h
    )
    cv2.rectangle(canvas, (x, y), (x + width, y + 34), PANEL_ALT, -1)
    draw_text(canvas, title, x + 10, y + 23, TEXT, 0.58, 1)
    if subtitle:
        text_size = cv2.getTextSize(subtitle, cv2.FONT_HERSHEY_SIMPLEX, 0.45, 1)[0]
        draw_text(
            canvas,
            subtitle,
            x + width - text_size[0] - 10,
            y + 22,
            MUTED,
            0.45,
            1,
        )


def draw_text(
    image: np.ndarray,
    text: str,
    x: int,
    y: int,
    color: tuple[int, int, int] = TEXT,
    scale: float = 0.55,
    thickness: int = 1,
) -> None:
    cv2.putText(
        image,
        text,
        (x, y),
        cv2.FONT_HERSHEY_SIMPLEX,
        scale,
        color,
        thickness,
        cv2.LINE_AA,
    )


def draw_centered_text(
    image: np.ndarray,
    text: str,
    y: int,
    color: tuple[int, int, int],
    scale: float,
) -> None:
    width = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, scale, 1)[0][0]
    draw_text(image, text, max(0, (image.shape[1] - width) // 2), y, color, scale)


def draw_tag(
    image: np.ndarray,
    text: str,
    anchor: tuple[int, int],
    color: tuple[int, int, int],
) -> None:
    x, y = anchor
    size = cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 0.45, 1)[0]
    x = int(np.clip(x, 0, max(0, image.shape[1] - size[0] - 8)))
    y = int(np.clip(y, size[1] + 7, image.shape[0] - 2))
    cv2.rectangle(image, (x, y - size[1] - 7), (x + size[0] + 7, y + 2), color, -1)
    draw_text(image, text, x + 4, y - 2, (18, 24, 31), 0.45, 1)


def panel(
    canvas: np.ndarray, x: int, y: int, width: int, height: int, title: str
) -> None:
    cv2.rectangle(canvas, (x, y), (x + width, y + height), PANEL, -1)
    cv2.rectangle(canvas, (x, y), (x + width, y + height), GRID, 1)
    draw_text(canvas, title.upper(), x + 14, y + 26, CYAN, 0.55, 1)


def draw_metric(
    canvas: np.ndarray,
    x: int,
    y: int,
    label: str,
    value: str,
    color: tuple[int, int, int] = TEXT,
) -> None:
    draw_text(canvas, label, x, y, MUTED, 0.48, 1)
    draw_text(canvas, value, x + 170, y, color, 0.58, 1)


def risk_color(score: float) -> tuple[int, int, int]:
    if not math.isfinite(score):
        return MUTED
    if score >= 70:
        return RED
    if score >= 35:
        return AMBER
    return GREEN


def build_series(frames: list[dict[str, Any]]) -> dict[str, np.ndarray]:
    def values(extractor: Any) -> np.ndarray:
        return np.asarray([safe_float(extractor(frame)) for frame in frames], dtype=float)

    return {
        "timestamp": values(lambda frame: frame.get("timestamp")),
        "speed": values(lambda frame: frame_value(frame, "ego", "speed_kmh")),
        "long_accel": values(
            lambda frame: frame_value(frame, "ego", "longitudinal_accel")
        ),
        "lat_accel": values(
            lambda frame: frame_value(frame, "ego", "lateral_accel")
        ),
        "ttc": values(lambda frame: frame.get("min_ttc")),
        "risk": values(lambda frame: frame_value(frame, "risk", "final_risk_score")),
        "alertness": values(
            lambda frame: frame_value(frame, "driver", "alertness_score")
        ),
    }


def draw_strip_chart(
    canvas: np.ndarray,
    rect: tuple[int, int, int, int],
    values: np.ndarray,
    current_index: int,
    label: str,
    color: tuple[int, int, int],
    fixed_range: tuple[float, float] | None = None,
    threshold: float | None = None,
) -> None:
    x, y, width, height = rect
    cv2.rectangle(canvas, (x, y), (x + width, y + height), PANEL_ALT, -1)
    cv2.rectangle(canvas, (x, y), (x + width, y + height), GRID, 1)
    plot_x = x + 118
    plot_y = y + 9
    plot_w = width - 132
    plot_h = height - 18
    draw_text(canvas, label, x + 10, y + 24, MUTED, 0.46, 1)

    finite = values[np.isfinite(values)]
    if finite.size == 0:
        draw_text(canvas, "no ground truth", plot_x + 10, y + 24, MUTED, 0.44, 1)
        return
    if fixed_range:
        lower, upper = fixed_range
    else:
        lower = float(np.nanpercentile(finite, 3))
        upper = float(np.nanpercentile(finite, 97))
        if math.isclose(lower, upper):
            lower -= 1.0
            upper += 1.0
    upper = max(upper, lower + 1e-6)

    if threshold is not None and lower <= threshold <= upper:
        threshold_y = int(plot_y + plot_h - (threshold - lower) / (upper - lower) * plot_h)
        cv2.line(
            canvas,
            (plot_x, threshold_y),
            (plot_x + plot_w, threshold_y),
            AMBER,
            1,
            cv2.LINE_AA,
        )

    valid_points: list[tuple[int, int]] = []
    for index, value in enumerate(values):
        if not math.isfinite(value):
            if len(valid_points) > 1:
                cv2.polylines(
                    canvas, [np.asarray(valid_points)], False, color, 1, cv2.LINE_AA
                )
            valid_points = []
            continue
        px = int(plot_x + index / max(1, len(values) - 1) * plot_w)
        clipped = float(np.clip(value, lower, upper))
        py = int(plot_y + plot_h - (clipped - lower) / (upper - lower) * plot_h)
        valid_points.append((px, py))
    if len(valid_points) > 1:
        cv2.polylines(
            canvas, [np.asarray(valid_points)], False, color, 1, cv2.LINE_AA
        )

    playhead_x = int(plot_x + current_index / max(1, len(values) - 1) * plot_w)
    cv2.line(
        canvas,
        (playhead_x, plot_y),
        (playhead_x, plot_y + plot_h),
        TEXT,
        1,
        cv2.LINE_AA,
    )
    current = values[current_index] if current_index < len(values) else math.nan
    draw_text(
        canvas,
        format_number(current, 2),
        x + 63,
        y + 24,
        color if math.isfinite(current) else MUTED,
        0.48,
        1,
    )


class TripRenderer:
    def __init__(
        self,
        trip_dir: Path,
        depth_policy: str = "previous",
        depth_max: float = 80.0,
        label_dir_name: str = "label_2",
    ) -> None:
        self.trip_dir = trip_dir
        self.document = load_trip_document(trip_dir)
        self.frames = self.document.get("frames", [])
        if not self.frames:
            raise ValueError(f"No frames found in {trip_dir}")
        self.series = build_series(self.frames)
        self.depth_policy = depth_policy
        self.depth_max = depth_max
        self.label_dir_name = label_dir_name
        self.depth_ids = np.asarray(
            sorted(
                int(path.stem)
                for path in (trip_dir / "kitti" / "depth").glob("*.npy")
                if path.stem.isdigit()
            ),
            dtype=int,
        )
        self.default_fps = safe_float(
            self.document.get("metadata", {}).get("fps"), 20.0
        )

    def render(self, index: int) -> np.ndarray:
        index = int(np.clip(index, 0, len(self.frames) - 1))
        frame = self.frames[index]
        frame_id = int(frame.get("frame_id", index))
        stem = f"{frame_id:06d}"

        left_path = find_image(
            self.trip_dir / "kitti" / "image_2", (stem,)
        )
        right_path = find_image(
            self.trip_dir / "kitti" / "image_3", (stem,)
        )
        driver_path = find_image(
            self.trip_dir / "driver", (f"frame_{stem}", stem)
        )
        left = read_image_or_placeholder(left_path, 640, 360, "image_2 unavailable")
        right = read_image_or_placeholder(right_path, 640, 360, "image_3 unavailable")
        driver = read_image_or_placeholder(driver_path, 640, 360, "driver unavailable")

        calibration = parse_calibration(
            self.trip_dir / "kitti" / "calib" / f"{stem}.txt"
        )
        labels = parse_labels(
            self.trip_dir / "kitti" / self.label_dir_name / f"{stem}.txt"
        )
        left = draw_labels(left, labels, calibration.get("P2"), True)
        right = draw_labels(right, labels, calibration.get("P3"), False)

        depth_id = nearest_depth_frame(self.depth_ids, frame_id, self.depth_policy)
        depth_path = (
            self.trip_dir / "kitti" / "depth" / f"{depth_id:06d}.npy"
            if depth_id is not None
            else None
        )
        depth, depth_caption = colorize_depth(depth_path, self.depth_max)

        canvas = np.full((CANVAS_H, CANVAS_W, 3), BG, dtype=np.uint8)
        self._draw_header(canvas, index, frame)
        paste_panel(
            canvas,
            left,
            20,
            68,
            1050,
            700,
            "ROAD LEFT / image_2",
            f"{len(labels)} objects | {self.label_dir_name}",
        )
        paste_panel(canvas, right, 1090, 68, 400, 220, "ROAD RIGHT / image_3")
        driver_state = frame_value(frame, "driver", "state") or "unlabeled"
        paste_panel(
            canvas,
            driver,
            1090,
            304,
            400,
            220,
            "DRIVER / cabin",
            str(driver_state),
        )
        paste_panel(
            canvas,
            depth,
            1090,
            540,
            400,
            228,
            "DEPTH / ground truth",
            (
                f"src {depth_id:06d} | {depth_caption}"
                if depth_id is not None
                else "unavailable"
            ),
        )
        self._draw_side_metrics(canvas, index, frame, calibration, labels)
        self._draw_timeline(canvas, index)
        return canvas

    def _draw_header(
        self, canvas: np.ndarray, index: int, frame: dict[str, Any]
    ) -> None:
        timestamp = safe_float(frame.get("timestamp"))
        draw_text(canvas, "FLEETIQ // SYNCHRONIZED DRIVE VIEW", 20, 39, TEXT, 0.82, 2)
        draw_text(
            canvas,
            f"{self.trip_dir.name}   FRAME {index:04d}/{len(self.frames)-1:04d}   "
            f"T+{timestamp:06.2f}s",
            1220,
            38,
            CYAN,
            0.58,
            1,
        )
        cv2.line(canvas, (20, 56), (1900, 56), GRID, 1)

    def _draw_side_metrics(
        self,
        canvas: np.ndarray,
        index: int,
        frame: dict[str, Any],
        calibration: dict[str, np.ndarray],
        labels: list[KittiLabel],
    ) -> None:
        x, y, width = 1510, 68, 390
        panel(canvas, x, y, width, 304, "Telemetry and risk")
        ego = frame.get("ego", {}) if isinstance(frame.get("ego"), dict) else {}
        driver = frame.get("driver", {}) if isinstance(frame.get("driver"), dict) else {}
        risk = frame.get("risk", {}) if isinstance(frame.get("risk"), dict) else {}
        score = safe_float(risk.get("final_risk_score"))
        ttc = safe_float(frame.get("min_ttc"))
        metrics = (
            ("Speed", format_number(ego.get("speed_kmh"), 1, " km/h"), TEXT),
            ("Long. accel", format_number(ego.get("longitudinal_accel"), 2, " m/s2"), TEXT),
            ("Lat. accel", format_number(ego.get("lateral_accel"), 2, " m/s2"), TEXT),
            ("Min TTC", format_number(ttc, 2, " s"), RED if math.isfinite(ttc) and ttc < 2 else TEXT),
            ("Headway", format_number(frame.get("headway_sec"), 2, " s"), TEXT),
            ("Risk score", format_number(score, 1, " / 100"), risk_color(score)),
            ("Alertness", format_number(driver.get("alertness_score"), 2), TEXT),
            ("Targets", str(len(labels)), TEXT),
        )
        for row, (label, value, color) in enumerate(metrics):
            draw_metric(canvas, x + 14, y + 58 + row * 29, label, value, color)

        panel(canvas, x, 386, width, 184, "Driver state and active events")
        state_rows = (
            ("State", driver.get("state", "unlabeled")),
            ("Eyes", driver.get("eye_state", "--")),
            ("Head pose", driver.get("head_pose", "--")),
            ("Mouth", driver.get("mouth_state", "--")),
        )
        for row, (label, value) in enumerate(state_rows):
            draw_metric(canvas, x + 14, 430 + row * 27, label, str(value))
        active = frame.get("events_active", [])
        event_types = []
        if isinstance(active, list):
            event_types = [
                str(event.get("type", event.get("event_type", "event")))
                if isinstance(event, dict)
                else str(event)
                for event in active
            ]
        draw_text(
            canvas,
            "Events: " + (", ".join(event_types[:3]) if event_types else "none"),
            x + 14,
            552,
            AMBER if event_types else MUTED,
            0.43,
            1,
        )

        panel(canvas, x, 584, width, 184, "Calibration")
        p2 = calibration.get("P2")
        p3 = calibration.get("P3")
        if p2 is None:
            draw_text(canvas, "Calibration unavailable", x + 14, 630, MUTED, 0.5, 1)
            return
        fx, fy, cx, cy = p2[0, 0], p2[1, 1], p2[0, 2], p2[1, 2]
        baseline = abs(p3[0, 3] / p3[0, 0] - p2[0, 3] / p2[0, 0]) if p3 is not None else math.nan
        calibration_rows = (
            f"fx={fx:.1f}  fy={fy:.1f}",
            f"cx={cx:.1f}  cy={cy:.1f}",
            f"stereo baseline={format_number(baseline, 3, ' m')}",
            f"P2 row0 [{p2[0,0]:.1f}, {p2[0,1]:.1f}, {p2[0,2]:.1f}, {p2[0,3]:.1f}]",
            f"P3 Tx={format_number(p3[0,3] if p3 is not None else None, 1)}",
        )
        for row, text in enumerate(calibration_rows):
            draw_text(canvas, text, x + 14, 627 + row * 27, TEXT if row < 3 else MUTED, 0.43, 1)

    def _draw_timeline(self, canvas: np.ndarray, index: int) -> None:
        panel(canvas, 20, 786, 1880, 274, "Full-trip telemetry timeline")
        draw_strip_chart(
            canvas,
            (36, 826, 1848, 48),
            self.series["speed"],
            index,
            "SPEED",
            CYAN,
            fixed_range=(0, max(120.0, float(np.nanmax(self.series["speed"])) + 5)),
        )
        draw_strip_chart(
            canvas,
            (36, 884, 1848, 48),
            self.series["long_accel"],
            index,
            "LONG ACC",
            GREEN,
            fixed_range=(-8, 8),
            threshold=-4,
        )
        draw_strip_chart(
            canvas,
            (36, 942, 1848, 48),
            self.series["ttc"],
            index,
            "MIN TTC",
            AMBER,
            fixed_range=(0, 8),
            threshold=2,
        )
        draw_strip_chart(
            canvas,
            (36, 1000, 1848, 48),
            self.series["risk"],
            index,
            "RISK",
            RED,
            fixed_range=(0, 100),
            threshold=70,
        )


def default_output(trip_name: str, mode: str, frame_id: int | None) -> Path:
    output_dir = PROJECT_ROOT / "artifacts" / "renders"
    output_dir.mkdir(parents=True, exist_ok=True)
    if mode == "frame":
        return output_dir / f"{trip_name}_frame_{frame_id or 0:06d}.png"
    return output_dir / f"{trip_name}_drive_dashboard.mp4"


def run_frame(renderer: TripRenderer, index: int, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    frame = renderer.render(index)
    if not cv2.imwrite(str(output), frame):
        raise IOError(f"Could not write image to {output}")
    print(f"Rendered frame {index}: {output}")


def run_video(
    renderer: TripRenderer,
    start: int,
    end: int,
    fps: float,
    output: Path,
) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(
        str(output),
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (CANVAS_W, CANVAS_H),
    )
    if not writer.isOpened():
        raise IOError(f"OpenCV could not open the MP4 writer for {output}")
    try:
        for index in range(start, end + 1):
            writer.write(renderer.render(index))
            if index == start or (index - start + 1) % 50 == 0 or index == end:
                print(f"Rendered {index - start + 1}/{end - start + 1} frames")
    finally:
        writer.release()
    print(f"Rendered video: {output}")


def run_window(
    renderer: TripRenderer,
    start: int,
    end: int,
    fps: float,
    speed: float,
) -> None:
    title = "FleetIQ synchronized drive view"
    cv2.namedWindow(title, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(title, 1440, 810)
    index = start
    paused = False
    delay_ms = max(1, int(1000 / max(0.1, fps * speed)))
    while True:
        tick = time.perf_counter()
        cv2.imshow(title, renderer.render(index))
        key = cv2.waitKey(0 if paused else delay_ms) & 0xFF
        if key in (27, ord("q")):
            break
        if key == ord(" "):
            paused = not paused
        elif key in (ord("a"), 81):
            index = max(start, index - 1)
            paused = True
        elif key in (ord("d"), 83):
            index = min(end, index + 1)
            paused = True
        elif key == ord("s"):
            output = default_output(renderer.trip_dir.name, "frame", index)
            cv2.imwrite(str(output), renderer.render(index))
            print(f"Saved snapshot: {output}")
        elif not paused:
            index = start if index >= end else index + 1
        elapsed = (time.perf_counter() - tick) * 1000
        if not paused and elapsed > delay_ms * 2:
            print(f"Warning: rendering frame {index} took {elapsed:.0f} ms")
    cv2.destroyAllWindows()


def main() -> None:
    args = parse_args()
    root = args.dataset_root.resolve()
    if args.list_trips:
        trips = discover_trips(root)
        if not trips:
            print(f"No trips found under {root}")
            return
        print(f"Trips under {root}:")
        for trip in trips:
            print(f"  {trip.name}")
        return

    trip_dir = resolve_trip(root, args.trip)
    renderer = TripRenderer(
        trip_dir,
        args.depth_policy,
        args.depth_max,
        args.label_dir_name,
    )
    start = int(np.clip(args.start, 0, len(renderer.frames) - 1))
    end = (
        len(renderer.frames) - 1
        if args.end is None
        else int(np.clip(args.end, start, len(renderer.frames) - 1))
    )
    fps = args.fps or renderer.default_fps or 20.0

    if args.mode == "frame":
        index = args.frame if args.frame is not None else start
        index = int(np.clip(index, start, end))
        output = (args.output or default_output(trip_dir.name, "frame", index)).resolve()
        run_frame(renderer, index, output)
    elif args.mode == "video":
        output = (args.output or default_output(trip_dir.name, "video", None)).resolve()
        run_video(renderer, start, end, fps, output)
    else:
        run_window(renderer, start, end, fps, args.speed)


if __name__ == "__main__":
    main()
